apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ${SECRET_NAME}-role
rules:
# Add permissions for your operator <--------------------------------
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get", "watch"] 