apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ${SECRET_NAME}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ${SECRET_NAME}-role
subjects:
- kind: ServiceAccount
  name: ${SECRET_NAME}-sa
  namespace: ${NAMESPACE} 